name: Bytez AI Auto-Fix
on:
  issue_comment:
    types: [created]

jobs:
  bytez-fix:
    if: startsWith(github.event.comment.body, '/bytez fix')
    runs-on: docker
    container:
      image: python:3.9-slim
      
    steps:
      - name: Install System Deps
        run: apt-get update && apt-get install -y git

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Python Deps
        run: pip install requests

      - name: Run Bytez Fix
        env:
          BYTEZ_API: ${{ secrets.BYTEZ_API }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_SERVER_URL: ${{ gitea.server_url }}
          GITEA_REPO: ${{ gitea.repository }}
          GITEA_PR_NUMBER: ${{ github.event.issue.number }}
        run: python scripts/ai_fix_bytez.py
