name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: docker  # Usa o seu zimaos-runner
    container:
      image: nikolaik/python-nodejs:python3.10-nodejs18
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pip install requests

      - name: Gemini Review
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITEA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITEA_SERVER_URL: ${{ gitea.server_url }}
          GITEA_REPO: ${{ gitea.repository }}
          GITEA_PR_NUMBER: ${{ gitea.event.pull_request.number }}
        run: python scripts/ai_review.py