name: Obsidian SQL Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: docker
    container:
      image: alpine:latest

    steps:
      - name: Install tools
        run: apk add --no-cache zip

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate build exists
        run: |
          test -f main.js || (echo "main.js missing" && exit 1)
          test -f manifest.json || (echo "manifest.json missing" && exit 1)

      - name: Create ZIP
        run: |
          mkdir release
          cp main.js manifest.json styles.css release/
          cd release && zip ../obsidian-sql.zip * && cd ..

      - name: Create Gitea Release
        uses: gitea/act-release@v1
        with:
          files: obsidian-sql.zip
          tag_name: ${{ gitea.ref_name }}
          token: ${{ secrets.RELEASE_TOKEN }}
