name: Obsidian SQL CI/CD
run-name: Build & Release by @${{ github.actor }}

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'

jobs:
  build-and-artifact:
    # Ajustado para suas labels específicas
    runs-on: docker
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Production Build
        run: npm run build

      - name: Prepare Plugin Bundle
        run: |
          mkdir -p release
          cp main.js manifest.json styles.css release/
          # Usando zip disponível na imagem docker do runner
          cd release && zip ../obsidian-sql.zip * && cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: obsidian-sql-build
          path: obsidian-sql.zip
          retention-days: 7

  release:
    needs: build-and-artifact
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: docker
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: obsidian-sql-build

      - name: Create Gitea Release
        uses: https://github.com/actions/gitea-release-action@main
        with:
          files: "obsidian-sql.zip"
          name: "Release ${{ github.ref_name }}"
          token: "${{ secrets.RELEASE_TOKEN }}"
