name: SQL Notebook Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: docker
    container:
      image: alpine:latest

    steps:
      - name: Install tools
        run: apk add --no-cache git zip curl jq

      - name: Clone repository
        run: |
          git clone --depth=1 --branch ${{ gitea.ref_name }} \
          http://x-access-token:${{ secrets.RELEASE_TOKEN }}@192.168.1.217:3003/Diego/obsidian-sql.git .
      
      - name: Validate build
        run: |
          test -f main.js
          test -f manifest.json

      - name: Create ZIP
        run: |
          mkdir release
          cp main.js manifest.json styles.css release/
          cd release && zip ../sql-notebook.zip * && cd ..

      - name: Create Gitea Release
        run: |
          curl -X POST "http://192.168.1.217:3003/api/v1/repos/Diego/obsidian-sql/releases" \
            -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"tag_name\": \"${{ gitea.ref_name }}\",
              \"name\": \"${{ gitea.ref_name }}\",
              \"body\": \"Automated release\"
            }"

      - name: Upload asset
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
            http://192.168.1.217:3003/api/v1/repos/Diego/obsidian-sql/releases/tags/${{ gitea.ref_name }} | jq .id)

          curl -X POST \
            -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
            -F "attachment=@sql-notebook.zip" \
            "http://192.168.1.217:3003/api/v1/repos/Diego/obsidian-sql/releases/$RELEASE_ID/assets?name=sql-notebook.zip"
