name: Obsidian SQL CI/CD
run-name: Build & Release by @${{ github.actor }}

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'

jobs:
  build-and-artifact:
    runs-on: docker
    container:
      image: node:18-slim

    steps:
      - name: Install Zip Utility
        run: apt-get update && apt-get install -y zip

      - name: Checkout Code
        uses: gitea/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Production Build
        run: npm run build

      - name: Prepare Plugin Bundle
        run: |
          mkdir -p release
          cp main.js manifest.json styles.css release/
          cd release && zip ../obsidian-sql.zip * && cd ..

      - name: Upload Artifact
        uses: gitea/upload-artifact@v4
        with:
          name: obsidian-sql-build
          path: obsidian-sql.zip

  release:
    needs: build-and-artifact
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: docker
    container:
      image: node:18-slim
    
    steps:
      - name: Download Artifact
        uses: gitea/download-artifact@v4
        with:
          name: obsidian-sql-build

      - name: Create Gitea Release
        uses: https://github.com/actions/gitea-release-action@main
        with:
          files: "obsidian-sql.zip"
          name: "Release ${{ github.ref_name }}"
          token: "${{ secrets.RELEASE_TOKEN }}"
